type db_config = { host: String?, username: String?, password: String?, database: String? }

# Birthday Calculator
class BirthdayCalculator
  @db: Sequel::Database
  @days_until_end_of_the_year: Integer
  @persons: Array[Person]
  @today: Date

  attr_reader persons: Array[Person]

  def initialize: (?db_config) -> void

  def load_data: () -> Array[Person]

  def print_days_remaining: () -> void

  private

  def calculate_days_remaining: (Date birthday) -> Integer
end
